Carbon neutral option added the Missing Create Element and Append it to Current Node
gabrielbull/php-ups-api pull request #338
Opened 2022-02-25 12:34 UTC by Shehryar2

Carbon neutral option added the Missing Create Element and Append it to Current Node

2022-02-25 12:36 UTC, Shehryar2 commented
Hey Mate ( [ptondereau](https://github.com/ptondereau) ),  can you please have a look here and please merge it asap. Thanks.

2022-02-25 14:34 UTC, ptondereau requested changes

2022-02-25 14:34 UTC, ptondereau commented on README.md
> +15. [License](#license-section)
```suggestion
13. [Logging](#logging)
14. [License](#license-section)
```

2022-02-25 14:34 UTC, ptondereau commented on src/Entity/ShipmentServiceOptions.php
> +     */
```suggestion
```

2022-02-28 10:21 UTC, Shehryar2 reviewed
Good to go

2022-02-28 10:23 UTC, merged

2022-02-28 10:35 UTC, Shehryar2 commented
Make release also.
Thanks @ptondereau

2022-03-01 12:02 UTC, Shehryar2 commented
@ptondereau Hy Mate, can you please have some spare time to make the release for the latest merge. Thanks a lot.